# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](color_orange)$os$username$hostname[](bg:color_yellow fg:color_orange)\
$directory[](fg:color_yellow bg:color_aqua)\
$nodejs$bun$deno\
$java$kotlin$scala$gradle\
$lua$python$php$ruby$elixir\
$c$cpp$cmake$xmake\
$rust$go$zig$haskell[](fg:color_aqua bg:color_blue)\
$docker_context[](fg:color_blue bg:color_bg3)\
$git_branch$git_commit$git_state[](fg:color_bg3 bg:color_bg1)\
$git_status$git_metrics(fg:color_fg0 bg:color_bg1)[](fg:color_bg1)\
$fill\
[](color_bg1)$memory_usage\
[](fg:color_bg3 bg:color_bg1)$time$battery[](fg:color_bg3)\
$line_break$character"""

## GLOBAL OPTIONS
command_timeout = 200


palette = 'gruvbox_dark'
## COLOR THEME

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'


## OS, user, and host
[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[username]
disabled = false
show_always = true
style_user = "fg:color_fg0 bg:color_orange"
style_root = "fg:color_fg0 bg:color_orange"
format = '[$user ]($style)'

[hostname]
disabled = false
ssh_symbol = " "
ssh_only = true
style = "fg:color_fg0 bg:color_orange"
format = '[$ssh_symbol$hostname ]($style)'


## DIRECTORY
[directory]
home_symbol = "~"
truncation_length = 5
truncation_symbol = ""
style = "fg:color_fg0 bg:color_yellow"
read_only = " 󰌾"
read_only_style = "fg:color_red bg:color_yellow"
format = "[ $path]($style)[$read_only ]($read_only_style)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"repos" = "󰲋 "


## GIT INTEGRATION
[git_branch]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_bg3)]($style)'

[git_commit]
tag_symbol = ''
only_detached = true
style = "bg:color_bg3"
format = '[[ $symbol $hash$tag ](fg:color_fg0 bg:color_bg3)]($style)'

[git_state]
rebase = 'REBASING'
merge = 'MERGING'
revert = 'REVERTING'
cherry_pick = 'CHERRY-PICKING'
bisect = 'BISECTING'
style = "bg:color_bg3"
format = '[[ $state($progress_current/$progress_total) ](fg:color_fg0 bg:color_bg3)]($style)'

[git_status]
style = "bg:color_bg1"
format = '[[ ($all_status$ahead_behind )](fg:color_fg0 bg:color_bg1)]($style)'

[git_metrics]
disabled = false
added_style = "fg:color_green bg:color_bg1"
deleted_style = "fg:color_red bg:color_bg1"
format = '[([+$added ]($added_style))([-$deleted ]($deleted_style))](bg:color_bg1)'


## ADDITIONAL INFO
[fill]
symbol = "─"
style = "fg:color_bg1"

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg3"
format = '[[  $time ](fg:color_fg0 bg:color_bg3)]($style)'

[battery]
disabled = false
format = '[$symbol$percentage ](fg:color_fg0 bg:color_bg3)'

[[battery.display]]
threshold = 100

[package]
symbol = "󰏗 "

[memory_usage]
disabled = false
threshold = -1
symbol = "󰍛 "
style = "fg:color_fg0 bg:color_bg1"
format = '[ $symbol${ram}( | ${swap}) ]($style)'

[status]
symbol = " "


## PROMPT
[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❱](bold fg:color_aqua)'
error_symbol = '[❱](bold fg:color_red)'
vimcmd_symbol = '[❰](bold fg:color_purple)'
vimcmd_replace_one_symbol = '[❰](bold fg:color_purple)'
vimcmd_replace_symbol = '[❰](bold fg:color_purple)'
vimcmd_visual_symbol = '[❰](bold fg:color_yellow)'


## LANGUAGES AND FRAMEWORKS:

[nodejs]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'

[bun]
symbol = " "
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'

[deno]
symbol = " "
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'


[java]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'

[kotlin]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'

[scala]
symbol = " "
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'

[gradle]
symbol = " "
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'

[lua]
symbol = " "
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'

[python]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'

[php]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'

[ruby]
symbol = " "
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'

[elixir]
symbol = " "
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'


[c]
symbol = " "
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'

[cpp]
symbol = " "
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'

[cmake]
symbol = " "
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'

[xmake]
symbol = " "
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'


[rust]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'

[golang]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'

[zig]
symbol = " "
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'

[haskell]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol ](fg:color_fg0 bg:color_aqua)]($style)'


[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = ""
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
Zorin = " "


[docker_context]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $context) ](fg:color_fg0 bg:color_blue)]($style)'

